# Generated by Django 5.1 on 2025-01-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва страви')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Ціна')),
                ('image', models.ImageField(blank=True, null=True, upload_to='dishes/', verbose_name='Фото страви')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Популярна страва')),
                ('is_new', models.BooleanField(default=False, verbose_name='Нова пропозиція')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оновлення')),
            ],
            options={
                'verbose_name': 'Страва',
                'verbose_name_plural': 'Страви',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва акції')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис')),
                ('start_date', models.DateField(verbose_name='Дата початку')),
                ('end_date', models.DateField(verbose_name='Дата завершення')),
                ('image', models.ImageField(blank=True, null=True, upload_to='promotions/', verbose_name='Зображення акції')),
                ('active', models.BooleanField(default=True, verbose_name='Активна пропозиція')),
            ],
            options={
                'verbose_name': 'Пропозиція',
                'verbose_name_plural': 'Пропозиції',
                'ordering': ['-start_date'],
            },
        ),
    ]
