# Generated by Django 5.1 on 2025-02-12 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_alter_dish_options_dish_created_at_dish_is_new_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Телефон')),
                ('address', models.TextField(verbose_name='Адреса доставки')),
                ('payment_method', models.CharField(choices=[('cash', 'Готівка'), ('card', 'Картка')], default='cash', max_length=10, verbose_name='Спосіб оплати')),
                ('status', models.CharField(choices=[('pending', 'Очікується'), ('confirmed', 'Підтверджено'), ('preparing', 'Готується'), ('delivering', 'Доставляється'), ('completed', 'Виконано'), ('canceled', 'Скасовано')], default='pending', max_length=15, verbose_name='Статус замовлення')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Кількість')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dish', verbose_name='Страва')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='orders.order', verbose_name='Замовлення')),
            ],
        ),
    ]
